// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundingBox } from "./BoundingBox";

export type GetVideoFrameResponse = { valid: boolean, image_b64: string, bboxes: Array<BoundingBox>, langs: Array<number>, };
