// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubocrProgress = { is_finished: number, start_us: bigint, current_us: bigint, duration_us: bigint, speed_up: number, };
