// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetVideoResponse = { valid: boolean, width: number, height: number, start_us: number, duration_us: number, };
