// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubtitleAnchor = { center_x: number, center_y: number, height: number, lang: number, is_primary: number, avg_width: number, min_width: number, mid_width: number, max_width: number, };
